### ISSUE TITLE
'Utilize as much as possible' not behaving as expected

### ISSUE THREAD

**Issue by far-blue** [jenkinsci/nomad-plugin#10]
Maybe I've mis-understood something but I set the nomad-cloud config to 'Utilize as much as possible' and scaled back my normal slave nodes to minimum but jobs were simply queueing rather than new nomad-cloud nodes spinning up. Any idea how to fix this? It works when I restrict where a build can run to just the nomad cloud but I'd prefer not to do that.

**Comment by antweiss** [comment]
@far-blue  - that's pretty easy - just leave the label definition on your Nomad slave template empty, or use the same label you're using for rest of the slaves.

**Comment by far-blue** [comment]
thanks for the help - I'd never have thought of leaving the labels empty :) With 'swarm' slaves the existence of a label doesn't prevent jobs being allocated. Got it all working nicely now with a mix of on-demand and static slaves (swarm slaves, still managed through Nomad).
