### ISSUE TITLE
Removal of Workspace root option causes fallback to system wide default

### ISSUE THREAD

**Issue by jdelee** [jenkinsci/nomad-plugin#102]
Jenkins and plugins versions report:

```
Jenkins: 2.303.2
OS: Linux - 5.11.0-1020-aws
---
nomad:0.9.0

```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
ubuntu 20.0.4
```

In release 0.8.0 `Workspace root` was used to specify the value of `-workDir` executed by the slave/agent.jar, but it also modified the `remoteFS` property for the node affecting the location of the workspace on the remote system.

With the removal of this option, the workspaceDir on the remote now defaults to the system property value `hudson.model.slave.workspaceDir`

please restore the ability to specify `remoteFS` for the remote node to accommodate setting unique workspaceDirs

**Comment by multani** [comment]
@jdelee I merged and release @j3t fix in [v0.9.1](https://github.com/jenkinsci/nomad-plugin/releases/tag/v0.9.1): you should be able to configure the root workspace again and reuse it in the template via the `%WORKER_DIR%` template variable.
