### ISSUE TITLE
Fails with Nomad 0.5 - most likely due to changes in the disk requirement config

### ISSUE THREAD

**Issue by far-blue** [jenkinsci/nomad-plugin#11]
Nomad 0.5.0 moves disk size requirement specification out of the task and into a new 'ephemeral_disk' element on the task group. This means jobs submitted by the jenkins nomad plugin are invalid and fail.

**Comment by cprenzberg** [comment]
Seeing the same issue

**Comment by antweiss** [comment]
Fixed in release 0.4
