### ISSUE TITLE
Support nomad constraints

### ISSUE THREAD

**Issue by gabordugov** [jenkinsci/nomad-plugin#15]
Hey it would be great if this plugin also supports nomad constraints https://www.nomadproject.io/docs/job-specification/constraint.html . It will allow to restrict list of nodes where jenkins slave can be launched.  For example, if nomad manages Linux and Windows nodes at the same time and we want to launch Jenkins slave in docker container built for Linux, it will be necessary to avoid launching it on Windows hosts. 
What do you think?

**Comment by antweiss** [comment]
I agree this would be a welcome addition - we currently have an issue with some very resource-heavy jobs that we would only want to send to specific nodes (those with more horsepower). I'll see if  can look into this but don't expect this to be fast.

**Comment by lucalandi** [comment]
This would be a really useful feature. I would be more than happy to contribute.

**Comment by jippi** [comment]
@lucalandi amazing ! :)

**Comment by scarvel8** [comment]
I have just opened a pull request that adds this functionality: https://github.com/jenkinsci/nomad-plugin/pull/17

**Comment by jovandeginste** [comment]
@jippi any reason not to merge the PR?

**Comment by jamesdmorgan** [comment]
Looking forward to this addition. Thanks to all those involved

**Comment by vincenthuynh** [comment]
Built the plugin off master with `mvn install` and uploaded to Jenkins. Had to update pom.xml to match my nomad version but the constraint property works! Thanks @scarvel8 !

**Comment by peimanja** [comment]
Why the latest plugin available on Jenkins is 0.4? so many commits have already been merged since then.
@vincenthuynh How did you manage to build the plugin? mine keeps failing from master.

**Comment by phedoreanu** [comment]
Closing as #17 is merged.
