### ISSUE TITLE
Bug in Nomad causing allocations history to grow for ever.

### ISSUE THREAD

**Issue by pawbur** [jenkinsci/nomad-plugin#16]
Hi,

This is not a real bug in nomad-plugin but an information that might be helpful for someone.

There is a bug in Nomad that id doesn't GC 'batch' jobs that have been stopped:
https://github.com/hashicorp/nomad/commit/9ef3b6a#diff-24d8e009cefba6873759e3745dbf5914R195

This is causing allocations history to never get GCed. This caused nomad to constantly increase amount of writes to raft.db. For us in our small nomad cluster for Jenkins usage this caused noticeable load on EBS volmes.

As a workaround I changed job type to service:
https://github.com/pawbur/nomad-plugin/commit/b3287ce0414096143cdf3941dd0099a95674fba3

I'm not sure if this should be merged as it potentially increases number of situation when we can end up with some disconnected slaves living in nomad cluster but given that as a batch jobs they also don't end without being stopped by Jenkins this might not be such a big issue.

**Comment by jippi** [comment]
This has been fixed in upstream nomad, thus closing :)
