### ISSUE TITLE
Support windows slaves

### ISSUE THREAD

**Issue by pvandervelde** [jenkinsci/nomad-plugin#18]
We would love to use the Nomad plugin to schedule agents in Windows Containers, however it looks like the current code only allows scheduling agents on Linux given that it uses Bash to start the slaves.

**Comment by scarvel8** [comment]
@pvandervelde Try using a newer version of the Nomad plugin, it works for me with Windows containers. https://jenkins.ci.cloudbees.com/job/plugins/job/nomad-plugin/2/org.jenkins-ci.plugins$nomad/

**Comment by pvandervelde** [comment]
Sweet I shall test as soon as we've got it set up!

**Comment by jippi** [comment]
Can this issue be closed?

**Comment by pvandervelde** [comment]
Yeah close it for now. Will reopen if it doesn't work. We're still working on our configuration / environment.
