### ISSUE TITLE
Exception raised when no datacenter is given

### ISSUE THREAD

**Issue by zstyblik** [jenkinsci/nomad-plugin#22]
Hello,

I'm not sure whether it's possible or not to return error message to the user rather than crashing with exception. If it is, it would be nice.

When no datacenter is given and datacenter box is left empty, exception is raised. I know (now) that datacenter is mandatory attribute and cannot be empty, but it'd be nice (if possible) to handle this error rather than raising exception.

Thank you.

**Comment by zstyblik** [comment]
Actually, it seems the above is valid for more than datacenter. And it's rather hard to track down which attribute is mandatory and which isn't(as a matter of fact, it seems all attributes are mandatory).

**Comment by multani** [comment]
#82 (v0.9+) removed most of the fields and it's not possible to not set the datacenter field anymore.

We should probably check that all the fields are correctly parsed anyway.
