### ISSUE TITLE
Support To mount nfs option in prefix command

### ISSUE THREAD

**Issue by thatsk** [jenkinsci/nomad-plugin#28]
Hello Team, 
If i want to mount NFS in docker container. If we are integrating nomad with jenkins and container wants the nfs mount which is in previlieged mode. How to do that please suggest i am getting Policy allows no restarts.
If i want to start the conatiner as follows:-
docker run -v /sys/fs/cgroup:/sys/fs/cgroup:ro maci0/systemd

**Comment by zstyblik** [comment]
Hello @thatsk,

please, see https://github.com/jenkinsci/nomad-plugin/pull/23 which adds support to mount Host volumes. Privileged mode isn't necessary, however NFS volume must be mounted on the Host itself.

**Comment by thatsk** [comment]
Done thanks for info.

**Comment by zstyblik** [comment]
Cool. I'm glad you've figured it out together with @jovandeginste and found PR useful :)
