### ISSUE TITLE
Plugin finds second URL

### ISSUE THREAD

**Issue by fferguson** [jenkinsci/nomad-plugin#30]
We have our plugin configured to talk to nomad and itself via different routes.

Nomad URL goes via a public zone
And the Jenkins urls are via private zone (effectively direct to the IP)

 
![image](https://user-images.githubusercontent.com/26222166/35816893-d210c1f6-0a93-11e8-87c0-1b95b0e41a47.png)

When starting a job Jenkins is able to launch a nomad instance however when that instance then tries to communicate back to Jenkins it fails. This seems to be because it is using an incorrect URL.

The nomad logs state:

`Feb 05, 2018 4:38:07 PM hudson.remoting.jnlp.Main createEngine
INFO: Setting up agent: jenkins-230c548c56d06
Feb 05, 2018 4:38:07 PM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Feb 05, 2018 4:38:07 PM hudson.remoting.Engine startEngine
WARNING: No Working Directory. Using the legacy JAR Cache location: /home/jenkins/.jenkins/cache/jars
Feb 05, 2018 4:38:07 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [https://jenkins2.made-mgmt.com/, http://jenkins2.mademgmt.com:8080/]
Feb 05, 2018 4:38:07 PM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
INFO: Remoting server accepts the following protocols: [JNLP4-connect, Ping]
Feb 05, 2018 4:38:07 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Agent discovery successful
  Agent address: jenkins2.made-mgmt.com
  Agent port:    41665
  Identity:      1a:75:cc:d1:c6:0e:9d:a6:c2:4e:b6:93:cd:d2:5c:64
Feb 05, 2018 4:38:07 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Handshaking
Feb 05, 2018 4:38:07 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to jenkins2.made-mgmt.com:41665`

The important part is the line

`INFO: Locating server among [https://jenkins2.made-mgmt.com/, http://jenkins2.mademgmt.com:8080/]`

https://jenkins2.made-mgmt.com does exist but goes via a load balancer and is not the route into Jenkins nomad slaves should be using. If they go via the second URL it should work as expected. My question is, why is this other URL being found? and where from? Also How can I stop it from happening, so that the plugin uses the correct URL.

**Comment by phedoreanu** [comment]
I'm facing the same issue @fferguson. 

My guess is that is takes the 2nd URL from `Jenkins Location -> Jenkins URL`

```
INFO: Locating server among [http://178.82.14.185/, https://jenkins.example.com/]
May 03, 2018 3:14:56 PM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
INFO: Remoting server accepts the following protocols: [JNLP4-connect, Ping]
May 03, 2018 3:14:56 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Agent discovery successful
  Agent address: jenkins.example.com
  Agent port:    8182
  Identity:      75:b8:21:9d:81:48:b1:4f:29:02:8c:a6:41:bc:85:1d
May 03, 2018 3:14:56 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Handshaking
May 03, 2018 3:14:56 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to jenkins.example.com:50000
```
If you would take the 1st address, in my case, it would work! 😖 

I'm thinking of adding another config input field like `JENKINS_PRIVATE_IP`.

**Comment by phedoreanu** [comment]
@jippi @fferguson Please check out #33 😉

**Comment by phedoreanu** [comment]
Now the logs look much better:
```
May 07, 2018 10:52:58 AM hudson.remoting.jnlp.Main createEngine
INFO: Setting up agent: jenkins-356c5eac23de6
May 07, 2018 10:52:59 AM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
May 07, 2018 10:52:59 AM hudson.remoting.Engine startEngine
INFO: Using Remoting version: 3.20
May 07, 2018 10:52:59 AM hudson.remoting.Engine startEngine
May 07, 2018 10:52:59 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [https://jenkins.example.com/]
May 07, 2018 10:52:59 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
INFO: Remoting server accepts the following protocols: [JNLP4-connect, Ping]
May 07, 2018 10:52:59 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Agent discovery successful
  Agent address: 178.82.14.185
  Agent port:    50000
  Identity:      75:b8:21:9d:81:48:b1:4f:29:02:8c:a6:41:bc:85:1d
May 07, 2018 10:52:59 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Handshaking
May 07, 2018 10:52:59 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to 178.82.14.185:50000
May 07, 2018 10:52:59 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Trying protocol: JNLP4-connect
May 07, 2018 10:52:59 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Remote identity confirmed: 75:b8:21:9d:81:48:b1:4f:29:02:8c:a6:41:bc:85:1d
May 07, 2018 10:53:01 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connected
```
