### ISSUE TITLE
Support for volume mounts

### ISSUE THREAD

**Issue by far-blue** [jenkinsci/nomad-plugin#31]
It would be great to have support for host mounts. My build slaves do a lot of composer, npm etc. updating and currently the slaves don't have a shared cache. I'd like to be able to mount a known location on the host machine where I can setup the caches for these package managers.

Alternatively, if all the instances were part of a task group I could possibly use the alloc/ space Nomad makes available.

**Comment by zstyblik** [comment]
Hello,

I believe this feature has been added in https://github.com/jenkinsci/nomad-plugin/commit/046a6fb75cd3db75e87ef64f2c57dcd5837972d5 .

**Comment by thatsk** [comment]
https://github.com/jenkinsci/nomad-plugin/pull/23
