### ISSUE TITLE
NomadCloud's private "name" field shadows its public parent and produces NullPointerException in other plugins

### ISSUE THREAD

**Issue by multani** [jenkinsci/nomad-plugin#38]
[NomadCloud](https://github.com/jenkinsci/nomad-plugin/blob/master/src/main/java/org/jenkinsci/plugins/nomad/NomadCloud.java#L29) redefines the `name` attribute as a private, whereas [the parent class](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/slaves/Cloud.java#L99) (via `AbastractCloudImpl`) defines it as public.

This creates a situation where:

1. When Jenkins starts, it picks up the configuration from its configuration file
1. It loads the relevant `Cloud`s objects configured and deserialize somehow the configuration into these objects
1. This populate the private `name` field of the concrete `NomadCloud` object, and shadows the public `name` field of the parent class
1. There's now a situation where, considering we have a `cloud` object of type `NomadCloud`:
  * `cloud.name` is null (it's the public `name` field of the parent class)
  * `cloud.getName()` returns the actual name of the `NomadCloud` object

This triggers unrelated failures many other Cloud-like plugins which are calling the public [`Jenkins.CloudList.getByName()`](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/jenkins/model/Jenkins.java#L508) method because the `name` field is now `null` and `c.name.equals(name)` raises a `NullPointerException`.

**Comment by phedoreanu** [comment]
@multani please review?
