### ISSUE TITLE
Increase slave count instead of queuing jobs

### ISSUE THREAD

**Issue by adrianlop** [jenkinsci/nomad-plugin#4]
Hi Ivo,
First of all, thanks for plugin v0.2, new params work like a charm.

I would like to have several slaves building jenkins jobs, but now they only queue up and wait until the slave is free.
I found a workaround, which is adding a few templates with different tags, but I think it could be improved using Nomad group param `count = N` for dynamically spinning slave allocations in Nomad.

Also, I noticed that 1 slave has 1 executor, could this be changed too? This is, same slave allocation building 2 or N jobs at the same time.

what do you think?

**Comment by iverberk** [comment]
Hi @adrianlop, Jenkins determines how many slaves are being used to handle the job queue. How do you see the ```count = N``` parameter working here? I'll look into the executors but I think this is possible for sure.

**Comment by adrianlop** [comment]
Hi, the number of executors inside the slave is 1 (and it cannot be changed, Jenkins will throw an exception)
![image](https://cloud.githubusercontent.com/assets/2879742/17473398/978aa32c-5d50-11e6-9a8f-38d9c968c87f.png)

Nomad job count = 1,
![image](https://cloud.githubusercontent.com/assets/2879742/17473652/e318fafe-5d51-11e6-8390-efae04369260.png)
and it won't increase by itself. I'm queuing 4 builds, 1 of them will start building inside a nomad slaves, rest of them will wait for a slot.

any ideas? I can't find any jenkins param to increase number of slaves or executors.

thanks for the help!!!

**Comment by antweiss** [comment]
Yep, the question here is how Jenkins decides when it's time to try provisioning a new slave. 
Need to look more into this.
 Ivo, any insights?

**Comment by iverberk** [comment]
It's a mystery to me actually. I have never been quite able to find out how this works internally. It does use some kind of balancing algorithm too not spin up too many nodes. I'll try to find out more. We probably need to be able to set the number of executors. I'll look into the error. I don't think the nomad count setting will help much here. It would only start two (or more) nodes at the same time (could be useful, but better to let Jenkins handle it).

**Comment by antweiss** [comment]
I agree. Setting the number of executors should be easy to do and could be useful in certain scenarios, while spinning up more than one node at a time seems counterinituitive.

**Comment by antweiss** [comment]
Looks like this is something we need to implement for faster node bringup: https://github.com/KostyaSha/yet-another-docker-plugin/blob/master/yet-another-docker-plugin/src/main/java/com/github/kostyasha/yad/DockerProvisioningStrategy.java

**Comment by iverberk** [comment]
Ah interesting, I'll take a look at it and see if we can adopt it. If you have a PR that would be even better ;-) Thanks!

**Comment by antweiss** [comment]
No PR yet :) I hope to have time to try this early next week. Let's keep in sync so we don't duplicate efforts on this.
