### ISSUE TITLE
Support Vault Integration

### ISSUE THREAD

**Issue by julian-haase** [jenkinsci/nomad-plugin#58]
Hey there, it would be great if this plugin also supports nomad vault integration https://www.nomadproject.io/docs/vault-integration/index.html and https://www.nomadproject.io/docs/job-specification/template.html#vault-kv-api-v1.
Unlike Jenkins Secrets, it allows you to retrieve Secrets at container runtime, without telling the Jenkins slave where to get the necessary Secrets for the upcoming build process. I think this is the intended way to interact with Nomad and Vault.

In my opinion, this requires the following two things: 

1. specify a policy for getting a valid token (https://www.nomadproject.io/docs/job-specification/vault.html)
2. define a template stanza to retrieve the secrets (https://www.nomadproject.io/docs/job-specification/template.html#vault-kv-api-v2)

**Comment by phedoreanu** [comment]
Hey @julian-haase 

Feel free submit a PR, if you have time and energy!

**Comment by josemaia** [comment]
PR submitted for this issue, #69

**Comment by phedoreanu** [comment]
Merged. Thanks!
