### ISSUE TITLE
Ability to set the cpu_hard_limit to true on slaves

### ISSUE THREAD

**Issue by peimanja** [jenkinsci/nomad-plugin#62]
Right now there is no way to set the [`cpu_hard_limit`](https://www.nomadproject.io/docs/drivers/docker.html#cpu_hard_limit) in the slave templates. We have this issue that some slaves can consume the whole cpu power of the instance and affect other jobs.

>cpu_hard_limit - (Optional) true or false (default). Use hard CPU limiting instead of soft limiting. By default this is false which means soft limiting is used and containers are able to burst above their CPU limit when there is idle capacity.

**Comment by multani** [comment]
#81 (v0.9+) should give access to all the Nomad job settings now.
