### ISSUE TITLE
Problem adding ACL token

### ISSUE THREAD

**Issue by SimonVleugels** [jenkinsci/nomad-plugin#66]
I have jenkins deployed in a nomad cluster running with ACL enabled. For dynamic provisioning the jenkins slaves I'm required to add an ACL Token. In the cloud configuration I see that there is an option to add a token, but the drop-down menu is always empty. I can add a credential but what kind of credential should I use?  

There is no documentation about using ACL.

**Comment by jmartinspt** [comment]
You should use a "Secret text" credential.

**Comment by SimonVleugels** [comment]
Thank you that was it.
