### ISSUE TITLE
Nomad cloud is not listed in "Manage Nodes and Cloud"

### ISSUE THREAD

**Issue by gkoloventzos** [jenkinsci/nomad-plugin#74]
Hello,

As I have not found anywhere else to ask (if you have any please send me links), I will post an issue that I have.
I am trying to set nomad with the Jenkins plugin but even though the cloud is found (from the jcasc.yaml) in "Configure clouds" page, it is not listed on the "Manage Nodes and Cloud" page.

I am running Jenkins version 2.263.3 with Nomad plugin 0.7.1
![managenodes](https://user-images.githubusercontent.com/2745542/107669062-a6d58180-6c91-11eb-9c82-c9420d6efbbe.png)
![nomadcloud](https://user-images.githubusercontent.com/2745542/107669097-adfc8f80-6c91-11eb-85bb-e32e76708369.png)

**Comment by jmartinspt** [comment]
Hello.
The node will appears only when the nomad worker start. It's a dynamic node, not a static node. When you use nomad cloud, the node from template starts, run the pipeline/job and in the end is deleted.

**Comment by gkoloventzos** [comment]
Thanks @jmartinspt! It seems counter-intuitive to me that the cloud as a whole will not be present on the list. I will see if my jobs will run. 

I will close the ticket!
