### ISSUE TITLE
New release soon?

### ISSUE THREAD

**Issue by entasisj** [jenkinsci/nomad-plugin#75]
Hi,

is there a chance to have a new release of this plugin soon?
We would like to install from official Jenkins source instead of building the plugin locally and installing the build result. I think other users might also be interested.

**Comment by robichaud** [comment]
It would be greatly appreciated to get a new release soon!

**Comment by erasmussen39** [comment]
A new release with the fix for the Configure Clouds page would be hugely helpful.

**Comment by multani** [comment]
(moving the discussion from #73 in here) I made the request to become a maintainer: https://groups.google.com/g/jenkinsci-dev/c/SlUkpR01b5c

**Comment by multani** [comment]
I'll prepare a new release in the coming days (there's a slight issue with the current code that prevents this at the moment), I'll report back here :+1: .

**Comment by multani** [comment]
[v0.7.4](https://github.com/jenkinsci/nomad-plugin/releases/tag/v0.7.4) is out :tada:
