### ISSUE TITLE
Add support for agent.jar

### ISSUE THREAD

**Issue by attachmentgenie** [jenkinsci/nomad-plugin#76]
### Dependencies

Jenkins has deprecated the use of the word slave it seems in favor of the word agent. (See https://hub.docker.com/r/jenkins/agent.) This also means the target jar has changed names to agent.jar

### Feature Request

make the agent jar name configurable

**Comment by multani** [comment]
#82 (v0.9+) makes it possible to use `agent.jar` instead of `slave.jar`.
