### ISSUE TITLE
make this plugin show up in the list of cloud provider

### ISSUE THREAD

**Issue by attachmentgenie** [jenkinsci/nomad-plugin#79]
### Feature Request

Jenkins now has a admin function to add cloud workers, this seems to be based on some sort of label [1], the nomad plugin currently isnt tagged appropriately to show up in this list. Making sure the tag is available would make it easier for folks to find it

[1] http://jenkins.qa.vagrant/pluginManager/available?filter=Cloud+Providers

**Comment by multani** [comment]
I followed https://www.jenkins.io/doc/developer/publishing/documentation/#labeling-plugins to relabel the repository and added the `cloud` label, this should mark the plugin as being a "Cloud Provider", at some point (I'm not sure when the update-center gets updated.)

**Comment by attachmentgenie** [comment]
While testing 0.9.1 shows up correctly in the list of cloud providers, thanks!
